site_name: Home
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  languange: en
  palette:
    - schema: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode ### YamlMime:Module
      primary: teal
      accent: purple
    - schema: stale
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode ### YamlMime:Module
      primary: teal
      accent: lime